In [1]:
import numpy as np
import math
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import pickle
from sklearn.datasets import make_classification

## Part 1 - Linear Regression

### Problem 1 - Linear Regression with Direct Minimization

In [2]:
print('PROBLEM 1')
print('----------')

PROBLEM 1
----------


In [3]:
def learnOLERegression(X,y):
    # Inputs:                                                         
    # X = N x d 
    # y = N x 1                                                               
    # Output: 
    # w = d x 1 
    
    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    xTranspose = np.transpose(X)
    xTx = np.dot(xTranspose,X)
    xTxinverse = np.linalg.inv(xTx)
    xTxinversexT = np.dot(xTxinverse, xTranspose)
    w = np.dot(xTxinversexT, y)
    return w

In [4]:
def testOLERegression(w,Xtest,ytest):
    # Inputs:
    # w = d x 1
    # Xtest = N x d
    # ytest = N x 1
    # Output:
    # rmse = scalar value

    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    left = np.transpose(ytest - np.dot(Xtest,w))
    right = ytest-np.dot(Xtest,w)
    paran = np.dot (left,right)
    div = paran / 242
    rmse = np.sqrt(div)
    return rmse

In [5]:
Xtrain,ytrain,Xtest,ytest = pickle.load(open('diabetes.pickle','rb'),encoding='latin1')   
# add intercept
x1 = np.ones((len(Xtrain),1))
x2 = np.ones((len(Xtest),1))

Xtrain_i = np.concatenate((np.ones((Xtrain.shape[0],1)), Xtrain), axis=1)
Xtest_i = np.concatenate((np.ones((Xtest.shape[0],1)), Xtest), axis=1)

w = learnOLERegression(Xtrain,ytrain)
w_i = learnOLERegression(Xtrain_i,ytrain)

rmse = testOLERegression(w,Xtrain,ytrain)
rmse_i = testOLERegression(w_i,Xtrain_i,ytrain)
print('RMSE without intercept on train data - %.2f'%rmse)
print('RMSE with intercept on train data - %.2f'%rmse_i)

rmse = testOLERegression(w,Xtest,ytest)
rmse_i = testOLERegression(w_i,Xtest_i,ytest)
print('RMSE without intercept on test data - %.2f'%rmse)
print('RMSE with intercept on test data - %.2f'%rmse_i)


RMSE without intercept on train data - 138.20
RMSE with intercept on train data - 46.77
RMSE without intercept on test data - 297.06
RMSE with intercept on test data - 55.36


### Problem 2 - Linear Regression with Gradient Descent

In [6]:
print('PROBLEM 2')
print('----------')

PROBLEM 2
----------


In [7]:
def regressionObjVal(w, X, y):

    # compute squared error (scalar) with respect
    # to w (vector) for the given data X and y      
    #
    # Inputs:
    # w = d x 1
    # X = N x d
    # y = N x 1
    # Output:
    # error = scalar value

    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    Xw = np.dot(X,w)
    yXw = y-Xw
    transpose = np.transpose(yXw)
    leftright = np.dot(transpose[0],yXw)
    return .5*leftright


In [8]:
def regressionGradient(w, X, y):

    # compute gradient of squared error (scalar) with respect
    # to w (vector) for the given data X and y   
    
    # Inputs:
    # w = d x 1
    # X = N x d
    # y = N x 1
    # Output:
    # gradient = d length vector (not a d x 1 matrix)

    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE 
    error = regressionObjVal(w, X, y)
    error_gradient = np.gradient(error)
    #error_grad = np.zeros((error_gradient.shape[1],))
    return error_gradient

In [9]:
Xtrain,ytrain,Xtest,ytest = pickle.load(open('diabetes.pickle','rb'),encoding='latin1')   
# add intercept
Xtrain_i = np.concatenate((np.ones((Xtrain.shape[0],1)), Xtrain), axis=1)
Xtest_i = np.concatenate((np.ones((Xtest.shape[0],1)), Xtest), axis=1)
args = (Xtrain_i,ytrain)
opts = {'maxiter' : 50}    # Preferred value.    
w_init = np.zeros((Xtrain_i.shape[1],1))
soln = minimize(regressionObjVal, w_init, jac=regressionGradient, args=args,method='CG', options=opts)
w = np.transpose(np.array(soln.x))
w = w[:,np.newaxis]
rmse = testOLERegression(w,Xtrain_i,ytrain)
print('Gradient Descent Linear Regression RMSE on train data - %.2f'%rmse)
rmse = testOLERegression(w,Xtest_i,ytest)
print('Gradient Descent Linear Regression RMSE on test data - %.2f'%rmse)

Gradient Descent Linear Regression RMSE on train data - 167.09
Gradient Descent Linear Regression RMSE on test data - 158.70


## Part 2 - Linear Classification

### Problem 3 - Perceptron using Gradient Descent

In [10]:
print('PROBLEM 3')
print('----------')

PROBLEM 3
----------


In [11]:
def predictLinearModel(w,Xtest):
    # Inputs:
    # w = d x 1
    # Xtest = N x d
    # Output:
    # ypred = N x 1 vector of predictions

    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    #print(Xtest
    wx = np.dot(Xtest,w)
    #print(Xtest)
    for i in range (0,wx.shape[0]):
        if(wx[i]>=0):
            wx[i] = 1
        else:
            wx[i] = -1
    ypred = wx
    return ypred

In [12]:
def evaluateLinearModel(w,Xtest,ytest):
    # Inputs:
    # w = d x 1
    # Xtest = N x d
    # ytest = N x 1
    # Output:
    # acc = scalar values

    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    ypred = predictLinearModel(w,Xtest)
    counter = 0
    for i in range (0,Xtest.shape[0]):
        #print(i)
        if(ypred[i] == ytest[i]):
            counter+=1
    return counter/Xtest.shape[0]

In [13]:
Xtrain,ytrain, Xtest, ytest = np.load(open('sample.pickle','rb')) 
# add intercept
Xtrain_i = np.concatenate((np.ones((Xtrain.shape[0],1)), Xtrain), axis=1)
Xtest_i = np.concatenate((np.ones((Xtest.shape[0],1)), Xtest), axis=1)

args = (Xtrain_i,ytrain)
opts = {'maxiter' : 50}    # Preferred value.
w_init = np.zeros((Xtrain_i.shape[1],1))
soln = minimize(regressionObjVal, w_init, jac=regressionGradient, args=args,method='CG', options=opts)
w = np.transpose(np.array(soln.x))
w = w[:,np.newaxis]
acc = evaluateLinearModel(w,Xtrain_i,ytrain)
print('Perceptron Accuracy on train data - %.2f'%acc)
acc = evaluateLinearModel(w,Xtest_i,ytest)
print('Perceptron Accuracy on test data - %.2f'%acc)

Perceptron Accuracy on train data - 0.54
Perceptron Accuracy on test data - 0.45


### Problem 4 - Logistic Regression Using Newton's Method

In [158]:
print('PROBLEM 4')
print('----------')

PROBLEM 4
----------


In [159]:
def logisticObjVal(w, X, y):

    # compute log-loss error (scalar) with respect
    # to w (vector) for the given data X and y                               
    # Inputs:
    # w = d x 1
    # X = N x d
    # y = N x 1
    # Output:
    # error = scalar
    
    
    
    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    weight_transpose = np.transpose(w)
    sum = 0
    for i in range (0,X.shape[0]):
        wx = np.dot(weight_transpose,X[i])
        theta = (1 / (1+(math.exp(-(np.dot(weight_transpose,X[i]))))))
        y=0;
        if(theta>=0.5):
            y = 1
        else:
            y = -1
        sum += math.log10(1+(math.exp(np.dot(-y,wx))))
        sum=sum/X.shape[0]
    return sum


In [152]:
def logisticGradient(w, X, y):

    # compute the gradient of the log-loss error (vector) with respect
    # to w (vector) for the given data X and y  
    #
    # Inputs:
    # w = d x 1
    # X = N x d
    # y = N x 1
    # Output:
    # error = d length gradient vector (not a d x 1 matrix)

    weight_transpose = np.transpose(w)
    sum = 0
    for i in range (0,X.shape[0]):
        wx = np.dot(weight_transpose,X[i])
        theta = (1 / (1+(math.exp(-(np.dot(weight_transpose,X[i]))))))
        y=0;
        if(theta>=0.5):
            y = 1
        else:
            y = -1
        bottom = 1 + math.exp(np.dot(y,wx))
        top = y / bottom
        final = top * X[i]
        sum+=final
        gradient = -sum / X.shape[0]
    
    return gradient

In [153]:
def logisticHessian(w, X, y):

    # compute the Hessian of the log-loss error (matrix) with respect
    # to w (vector) for the given data X and y                               
    #
    # Inputs:
    # w = d x 1
    # X = N x d
    # y = N x 1
    # Output:
    # Hessian = d x d matrix
    
    # IMPLEMENT THIS METHOD - REMOVE THE NEXT LINE
    weight_transpose = np.transpose(w)
    sum = 0
    for i in range (0, X.shape[0]):
        wx = np.dot (weight_transpose,X[i])
        theta = (1 / (1+(math.exp(-(np.dot(weight_transpose,X[i]))))))
        y=0;
        if(theta>=0.5):
            y = 1
        else:
            y = -1
        top = math.exp(np.dot(y,wx))
        bottom = math.pow((1 + math.exp(np.dot(y,wx))),2)
        left = top / bottom
        right = np.dot(X[i],np.transpose(X[i]))
        inner = np.dot(left,right)
        sum +=inner
    hessian = -sum/X.shape[0]
    return hessian

In [154]:
Xtrain,ytrain, Xtest, ytest = np.load(open('sample.pickle','rb')) 
# add intercept
Xtrain_i = np.concatenate((np.ones((Xtrain.shape[0],1)), Xtrain), axis=1)
Xtest_i = np.concatenate((np.ones((Xtest.shape[0],1)), Xtest), axis=1)

args = (Xtrain_i,ytrain)
opts = {'maxiter' : 50}    # Preferred value.    
w_init = np.zeros((Xtrain_i.shape[1],1))
soln = minimize(logisticObjVal, w_init, jac=logisticGradient, hess=logisticHessian, args=args,method='Newton-CG', options=opts)
w = np.transpose(np.array(soln.x))
w = np.reshape(w,[len(w),1])
acc = evaluateLinearModel(w,Xtrain_i,ytrain)
print('Logistic Regression Accuracy on train data - %.2f'%acc)
acc = evaluateLinearModel(w,Xtest_i,ytest)
print('Logistic Regression Accuracy on test data - %.2f'%acc)

[-0.5        -1.10127802 -0.51150853]
[-0.22765726 -0.42257658 -0.1029574 ]
[-0.22765726 -0.42257658 -0.1029574 ]
[-0.22472813 -0.41585436 -0.09983575]
[-0.21338656 -0.38998947 -0.08795825]
[-0.17366024 -0.30165652 -0.04927547]
[-0.17366024 -0.30165652 -0.04927547]
[-0.17315045 -0.30055462 -0.04885752]
[-0.17112704 -0.29618779 -0.0472071 ]
[-0.1632809  -0.27935851 -0.04093785]
[-0.13556858 -0.2213488  -0.02059704]
[-0.13556858 -0.2213488  -0.02059704]
[-0.13521565 -0.22062989 -0.02038774]
[-0.13381376 -0.21777832 -0.01956122]
[-0.1283608  -0.20674913 -0.01642109]
[-0.10884685 -0.16815186 -0.00622092]
[-0.10884685 -0.16815186 -0.00622092]
[-0.1086062  -0.16768752 -0.00612319]
[-0.1076493  -0.16584348 -0.00573707]
[-0.10391186 -0.15867626 -0.00426789]
[-0.09031331 -0.13309887  0.00053105]
[-0.09031331 -0.13309887  0.00053105]
[-0.09015113 -0.13280021  0.00057408]
[-0.08950554 -0.13161255  0.00074416]
[-0.08697273 -0.12697182  0.00139258]
[-0.07759267 -0.11005729  0.00352438]
[-0.07759267

[-7.02024717e-05 -3.17103486e-05 -3.44981681e-06]
[-6.86220874e-05 -3.09585007e-05 -3.36935761e-06]
[-6.26510755e-05 -2.81281115e-05 -3.06687244e-06]
[-6.26510755e-05 -2.81281115e-05 -3.06687244e-06]
[-6.26441600e-05 -2.81248441e-05 -3.06652182e-06]
[-6.26165056e-05 -2.81117784e-05 -3.06511979e-06]
[-6.25060111e-05 -2.80595773e-05 -3.05951843e-06]
[-6.20659948e-05 -2.78517573e-05 -3.03722097e-06]
[-6.03369283e-05 -2.70360179e-05 -2.94973410e-06]
[-5.38925246e-05 -2.40087647e-05 -2.62552446e-06]
[-5.38925246e-05 -2.40087647e-05 -2.62552446e-06]
[-5.38854903e-05 -2.40054732e-05 -2.62517002e-06]
[-5.38573624e-05 -2.39923121e-05 -2.62375275e-06]
[-5.37449983e-05 -2.39397409e-05 -2.61809173e-06]
[-5.32978994e-05 -2.37306249e-05 -2.59557593e-06]
[-5.15466643e-05 -2.29125648e-05 -2.50753076e-06]
[-4.51023363e-05 -1.99168424e-05 -2.18555664e-06]
[-4.51023363e-05 -1.99168424e-05 -2.18555664e-06]
[-4.50958007e-05 -1.99138177e-05 -2.18522940e-06]
[-4.50696679e-05 -1.99017237e-05 -2.18392092e-06]


### Problem 5 - Support Vector Machines Using Gradient Descent

In [ ]:
print('PROBLEM 5')
print('----------')

In [ ]:
def trainSGDSVM(X,y,T,eta=0.01):
    # learn a linear SVM by implementing the SGD algorithm
    #
    # Inputs:
    # X = N x d
    # y = N x 1
    # T = number of iterations
    # eta = learning rate
    # Output:
    # weight vector, w = d x 1
    
    # IMPLEMENT THIS METHOD
    w = np.zeros([X.shape[1],1])
    return w

In [ ]:
Xtrain,ytrain, Xtest, ytest = np.load(open('sample.pickle','rb')) 
# add intercept
Xtrain_i = np.concatenate((np.ones((Xtrain.shape[0],1)), Xtrain), axis=1)
Xtest_i = np.concatenate((np.ones((Xtest.shape[0],1)), Xtest), axis=1)

args = (Xtrain_i,ytrain)
w = trainSGDSVM(Xtrain_i,ytrain,100,0.01)
acc = evaluateLinearModel(w,Xtrain_i,ytrain)
print('SVM Accuracy on train data - %.2f'%acc)
acc = evaluateLinearModel(w,Xtest_i,ytest)
print('SVM Accuracy on test data - %.2f'%acc)

### Problem 6 - Plotting decision boundaries

In [ ]:
print('Problem 6')
print('---------')

In [ ]:
def plotBoundaries(w,X,y):
    # plotting boundaries

    mn = np.min(X,axis=0)
    mx = np.max(X,axis=0)
    x1 = np.linspace(mn[1],mx[1],100)
    x2 = np.linspace(mn[2],mx[2],100)
    xx1,xx2 = np.meshgrid(x1,x2)
    xx = np.zeros((x1.shape[0]*x2.shape[0],2))
    xx[:,0] = xx1.ravel()
    xx[:,1] = xx2.ravel()
    xx_i = np.concatenate((np.ones((xx.shape[0],1)), xx), axis=1)
    ypred = predictLinearModel(w,xx_i)
    ax.contourf(x1,x2,ypred.reshape((x1.shape[0],x2.shape[0])),alpha=0.3,cmap='cool')
    ax.scatter(X[:,1],X[:,2],c=y.flatten())

In [ ]:
Xtrain,ytrain, Xtest, ytest = np.load(open('sample.pickle','rb')) 
# add intercept
Xtrain_i = np.concatenate((np.ones((Xtrain.shape[0],1)), Xtrain), axis=1)
Xtest_i = np.concatenate((np.ones((Xtest.shape[0],1)), Xtest), axis=1)

# Replace next three lines with code for learning w using the three methods
w_perceptron = np.zeros((Xtrain_i.shape[1],1))
w_logistic = np.zeros((Xtrain_i.shape[1],1))
w_svm = np.zeros((Xtrain_i.shape[1],1))
fig = plt.figure(figsize=(20,6))

ax = plt.subplot(1,3,1)
plotBoundaries(w_perceptron,Xtrain_i,ytrain)
ax.set_title('Perceptron')

ax = plt.subplot(1,3,2)
plotBoundaries(w_logistic,Xtrain_i,ytrain)
ax.set_title('Logistic Regression')

ax = plt.subplot(1,3,3)
plotBoundaries(w_svm,Xtrain_i,ytrain)
ax.set_title('SVM')
